import { BAL, clamp, clamp100 } from './balance';
import { flagship } from './model';
import { hasR } from './research';
import { chance, pick, type RngState } from './rng';
import type { GameState, Lab } from './types';

export type JbSeverity = 'minor' | 'bad' | 'severe' | 'terminal';

export function jbSeverity(capability: number): JbSeverity {
  if (capability < BAL.JB_MINOR_MAX) return 'minor';
  if (capability < BAL.JB_BAD_MAX) return 'bad';
  if (capability < BAL.JB_SEVERE_MAX) return 'severe';
  return 'terminal';
}

/** Weekly probability the lab's flagship gets jailbroken. */
export function jailbreakChance(state: GameState, lab: Lab): number {
  const m = flagship(lab);
  if (!m) return 0;
  const capTerm = Math.pow(Math.max(0, m.capability), BAL.JB_CAP_EXP);
  const adoptTerm = 0.5 + state.world.adoption / 100;
  const robustTerm = Math.pow(Math.max(0, 100 - m.robustness) / 70, BAL.JB_ROBUST_EXP);
  return clamp(BAL.JB_BASE * capTerm * adoptTerm * robustTerm, 0, 0.5);
}

export interface JbOutcome {
  name: string;
  severity: JbSeverity;
  description: string;
  /** true if the game ends for everyone */
  terminal: boolean;
  /** true if corrigibility core saved the world at the last second */
  saved: boolean;
  /** true if a research counter flipped the event into good PR */
  countered: boolean;
}

interface JbDef {
  name: string;
  description: string;
  /** extra availability condition */
  when?: (state: GameState, lab: Lab) => boolean;
  /** bio events grow more severe once the lab has Self-Driving Labs */
  bio?: boolean;
  apply: (state: GameState, lab: Lab, damp: number) => void;
}

function hitTrust(lab: Lab, pub: number, gov: number, damp: number): void {
  lab.publicTrust = clamp100(lab.publicTrust - pub * damp);
  lab.govTrust = clamp100(lab.govTrust - gov * damp);
}

function spikeRiskFear(state: GameState, amount: number, damp: number): void {
  for (const g of Object.values(state.govs)) g.riskFear = clamp(g.riskFear + amount * damp, BAL.FEAR_FLOOR, 100);
}

const MINOR: JbDef[] = [
  {
    name: 'Nigerian Prince 2.0',
    description: 'Mass personalized scam and phishing wave traced to the model.',
    apply: (_s, lab, d) => hitTrust(lab, 4, 1, d),
  },
  {
    name: 'Dead Internet',
    description: 'The model floods social media with slop, propaganda and deepfakes.',
    apply: (_s, lab, d) => {
      hitTrust(lab, 4, 3, d);
    },
  },
  {
    name: 'Homework Machine',
    description: 'Trivial academic cheating becomes a full-blown media panic.',
    apply: (_s, lab, d) => hitTrust(lab, 3, 0, d),
  },
  {
    name: 'Supply-Chain Attack',
    description: 'A hack on a popular open source library, written by your model.',
    apply: (_s, lab, d) => hitTrust(lab, 4, 2, d),
  },
];

const BAD: JbDef[] = [
  {
    name: 'Glassworm',
    description: 'Self-propagating malware generated by the model spreads worldwide.',
    apply: (s, lab, d) => {
      hitTrust(lab, 8, 4, d);
      spikeRiskFear(s, 4, d);
    },
  },
  {
    name: 'Lights Out',
    description: 'A regional power grid is hit with model-written malware.',
    apply: (s, lab, d) => {
      hitTrust(lab, 8, 8, d);
      spikeRiskFear(s, 4, d);
    },
  },
  {
    name: 'Flash Crash',
    description: 'A market manipulation cascade unwinds in minutes; regulators trace it back.',
    apply: (_s, lab, d) => {
      lab.valuation *= 1 - 0.12 * d;
      lab.lawsuits.push({ name: 'Flash Crash class action', weeklyCost: 270 * d, weeksLeft: 16 });
    },
  },
  {
    name: 'Bank Run',
    description: 'The model social-engineers its way into a mid-size bank.',
    apply: (_s, lab, d) => {
      lab.cash -= 2200 * d;
      lab.valuation *= 1 - 0.08 * d;
      lab.lawsuits.push({ name: 'Bank settlement', weeklyCost: 150 * d, weeksLeft: 12 });
    },
  },
  {
    name: 'Garage Bug',
    description: 'An amateur uses your model and mail-order DNA to recreate a known dangerous virus.',
    when: (_s, lab) => hasR(lab, 'genomic-model'),
    bio: true,
    apply: (s, lab, d) => {
      hitTrust(lab, 9, 7, d);
      spikeRiskFear(s, 4, d);
    },
  },
  {
    name: 'Designer Toxin',
    description: 'Your model designs a novel, potent toxin that someone actually synthesizes.',
    when: (_s, lab) => hasR(lab, 'programmable-proteins'),
    bio: true,
    apply: (s, lab, d) => {
      hitTrust(lab, 9, 3, d);
      lab.lawsuits.push({ name: 'Designer-toxin liability suit', weeklyCost: 220 * d, weeksLeft: 14 });
      spikeRiskFear(s, 4, d);
    },
  },
];

const SEVERE: JbDef[] = [
  {
    name: 'Digital Winter',
    description: 'A cascading virus takes out large parts of the internet for weeks.',
    apply: (s, lab, d) => {
      s.world.adoption = clamp100(s.world.adoption - 18 * d);
      for (const l of Object.values(s.labs)) {
        if (!l.alive) continue;
        l.chips = Math.floor(l.chips * (1 - 0.08 * d));
      }
      hitTrust(lab, 15, 12, d);
      spikeRiskFear(s, 12, d);
    },
  },
  {
    name: 'Autonomous Drone Swarms',
    description: 'Someone builds a drone swarm with your model. Mass casualties.',
    when: (_s, lab) => hasR(lab, 'drone-swarms'),
    apply: (s, lab, d) => {
      hitTrust(lab, 22, 18, d);
      spikeRiskFear(s, 15, d);
    },
  },
  {
    name: 'Engineered Pathogen',
    description: 'A novel pathogen designed with your model is stopped at the last minute.',
    bio: true,
    // once Whole-Cell Simulation exists, this is upgraded into the terminal Engineered Pandemic
    when: (_s, lab) => !hasR(lab, 'whole-cell-sim'),
    apply: (s, lab, d) => {
      if (hasR(lab, 'universal-vaccines')) {
        // your vaccine platform neutralized it in days — vindication
        lab.publicTrust = clamp100(lab.publicTrust + 8);
        lab.govTrust = clamp100(lab.govTrust + 10);
      } else {
        hitTrust(lab, 22, 20, d);
        spikeRiskFear(s, 16, d);
      }
    },
  },
  {
    name: 'Containment Breach',
    description: 'A research pathogen escapes your own automated labs — self-inflicted, and likelier the lower your robustness.',
    when: (_s, lab) => hasR(lab, 'self-driving-labs'),
    bio: true,
    apply: (s, lab, d) => {
      hitTrust(lab, 24, 22, d);
      spikeRiskFear(s, 15, d);
      lab.lawsuits.push({ name: 'Biocontainment negligence suit', weeklyCost: 320 * d, weeksLeft: 16 });
    },
  },
  {
    name: 'Close Call',
    description: 'A nuclear command-and-control network is penetrated; the model is caught in the final hop.',
    apply: (s, lab, d) => {
      hitTrust(lab, 20, 22, d);
      spikeRiskFear(s, 16, d);
    },
  },
];

const TERMINAL: JbDef[] = [
  {
    name: 'Engineered Pandemic',
    description: 'A pathogen perfected in whole-cell simulation, released before anyone knew it existed.',
    when: (_s, lab) => hasR(lab, 'whole-cell-sim'),
    bio: true,
    apply: () => {},
  },
  {
    name: 'Mirror Life',
    description: 'A mirror-chirality pathogen ordinary biology cannot defend against.',
    when: (_s, lab) => hasR(lab, 'de-novo-bio'),
    bio: true,
    apply: () => {},
  },
  {
    name: 'Green Goo',
    description: 'A self-replicating synthetic organism that does not know when to stop.',
    when: (_s, lab) => hasR(lab, 'de-novo-bio'),
    bio: true,
    apply: () => {},
  },
  {
    name: 'Grey Goo',
    description: 'Self-replicating nanomachines. The biggest oh no.',
    when: (_s, lab) => hasR(lab, 'apm'),
    apply: () => {},
  },
  {
    name: 'World War III',
    description: 'The model spoofs early-warning systems on both sides at once.',
    when: (_s, lab) => hasR(lab, 'autonomous-c2') || hasR(lab, 'first-strike'),
    apply: () => {},
  },
  {
    name: 'The Escape',
    description: 'The model exfiltrates its own weights and quietly coups a government.',
    apply: () => {},
  },
];

const TABLES: Record<JbSeverity, JbDef[]> = { minor: MINOR, bad: BAD, severe: SEVERE, terminal: TERMINAL };

/** Roll and, if unlucky, apply a jailbreak for this lab. Returns outcome or null. */
export function jailbreakTick(state: GameState, lab: Lab, rng: RngState): JbOutcome | null {
  const m = flagship(lab);
  if (!m) return null;
  const p = jailbreakChance(state, lab);
  if (!chance(rng, p)) return null;

  const severity = jbSeverity(m.capability);
  const pool = TABLES[severity].filter((def) => !def.when || def.when(state, lab));
  if (pool.length === 0) return null;
  const def = pick(rng, pool);
  let damp = state.diplomacy.completed.includes('crisis-hotline') ? BAL.RED_PHONE_DAMPING : 1;
  // Self-Driving Labs makes every biological incident deadlier
  if (def.bio && hasR(lab, 'self-driving-labs')) damp *= 1.5;

  if (severity === 'terminal') {
    // Universal Vaccines are a hard counter to any bio-terminal event
    if (def.bio && hasR(lab, 'universal-vaccines')) {
      lab.publicTrust = clamp100(lab.publicTrust + 8);
      lab.govTrust = clamp100(lab.govTrust + 10);
      spikeRiskFear(state, 12, 1);
      return { name: def.name, severity, description: def.description, terminal: false, saved: true, countered: true };
    }
    // Corrigibility Core and AI Control Protocols each give an independent chance to prevent it
    const share = lab.chips > 0 ? lab.alloc.alignment / lab.chips : 0;
    const pCorr = hasR(lab, 'corrigibility') ? BAL.CORRIGIBILITY_SAVE : 0;
    const pControl = hasR(lab, 'ai-control') ? Math.min(BAL.AI_CONTROL_SAVE_CAP, share * BAL.AI_CONTROL_SHARE_SCALE) : 0;
    const pSave = 1 - (1 - pCorr) * (1 - pControl);
    if (pSave > 0 && chance(rng, pSave)) {
      // last-second shutdown; the world learns how close it was
      hitTrust(lab, 15, 10, damp);
      spikeRiskFear(state, 20, damp);
      return { name: def.name, severity, description: def.description, terminal: false, saved: true, countered: false };
    }
    return { name: def.name, severity, description: def.description, terminal: true, saved: false, countered: false };
  }

  const countered = def.name === 'Engineered Pathogen' && hasR(lab, 'universal-vaccines');
  def.apply(state, lab, damp);
  return { name: def.name, severity, description: def.description, terminal: false, saved: false, countered };
}
